<?php

namespace Database\Seeders;

use App\Models\NiveauConfig;
use Illuminate\Database\Seeder;

class NiveauxConfigSeeder extends Seeder
{
    public function run(): void
    {
        // NOTE: ne pas utiliser json_encode() ici — le modèle a le cast 'array'
        // et encode lui-même. Passer des tableaux PHP bruts.
        $plans = [
            [
                'cle'                         => 'standard_mensuel',
                'label'                       => 'Standard Mensuel',
                'duree_jours'                 => 31,
                'prix_xof'                    => 3500,
                'prix_mensuel_equivalent_xof' => 3500,
                'is_actif'                    => true,
                'ordre_affichage'             => 1,
                'description_courte'          => 'Idéal pour démarrer',
                'config' => [
                    'max_assistants'          => 0,
                    'max_membres'             => 0,
                    'max_clients_par_mois'    => 50,
                    'max_photos_vip_par_mois' => null,
                    'max_factures_par_mois'   => 0,
                    'pts_par_client'          => 1,
                    'pts_par_commande'        => 1,
                    'pts_activation'          => 31,
                    'seuil_conversion_pts'    => 10000,
                    'photos_vip'              => false,
                    'facture_whatsapp'        => false,
                    'sauvegarde_auto'         => false,
                    'module_caisse'           => false,
                    'multi_ateliers'          => false,
                    'export_pdf'              => true,
                ],
            ],
            [
                'cle'                         => 'standard_annuel',
                'label'                       => 'Standard Annuel',
                'duree_jours'                 => 365,
                'prix_xof'                    => 35000,
                'prix_mensuel_equivalent_xof' => 2917,
                'is_actif'                    => true,
                'ordre_affichage'             => 2,
                'description_courte'          => "Économisez avec l'annuel",
                'config' => [
                    'max_assistants'          => 1,
                    'max_membres'             => 1,
                    'max_clients_par_mois'    => 80,
                    'max_photos_vip_par_mois' => null,
                    'max_factures_par_mois'   => 0,
                    'pts_par_client'          => 1,
                    'pts_par_commande'        => 1,
                    'pts_activation'          => 365,
                    'seuil_conversion_pts'    => 10000,
                    'photos_vip'              => false,
                    'facture_whatsapp'        => false,
                    'sauvegarde_auto'         => false,
                    'module_caisse'           => false,
                    'multi_ateliers'          => false,
                    'export_pdf'              => true,
                ],
            ],
            [
                'cle'                         => 'premium_mensuel',
                'label'                       => 'Premium Mensuel',
                'duree_jours'                 => 31,
                'prix_xof'                    => 7500,
                'prix_mensuel_equivalent_xof' => 7500,
                'is_actif'                    => true,
                'ordre_affichage'             => 3,
                'description_courte'          => 'Le plus populaire',
                'config' => [
                    'max_assistants'          => 1,
                    'max_membres'             => 3,
                    'max_clients_par_mois'    => 100,
                    'max_photos_vip_par_mois' => 5,
                    'max_factures_par_mois'   => 25,
                    'pts_par_client'          => 1,
                    'pts_par_commande'        => 1,
                    'pts_activation'          => 31,
                    'seuil_conversion_pts'    => 45000,
                    'photos_vip'             => true,
                    'facture_whatsapp'       => true,
                    'sauvegarde_auto'        => false,
                    'module_caisse'          => true,
                    'multi_ateliers'         => false,
                    'export_pdf'             => true,
                ],
            ],
            [
                'cle'                         => 'premium_annuel',
                'label'                       => 'Premium Annuel',
                'duree_jours'                 => 365,
                'prix_xof'                    => 75000,
                'prix_mensuel_equivalent_xof' => 6250,
                'is_actif'                    => true,
                'ordre_affichage'             => 4,
                'description_courte'          => 'Premium avec sauvegarde auto',
                'config' => [
                    'max_assistants'          => 2,
                    'max_membres'             => 5,
                    'max_clients_par_mois'    => 150,
                    'max_photos_vip_par_mois' => 15,
                    'max_factures_par_mois'   => null,
                    'pts_par_client'          => 2,
                    'pts_par_commande'        => 2,
                    'pts_activation'          => 365,
                    'seuil_conversion_pts'    => 45000,
                    'photos_vip'             => true,
                    'facture_whatsapp'       => true,
                    'sauvegarde_auto'        => true,
                    'module_caisse'          => true,
                    'multi_ateliers'         => false,
                    'export_pdf'             => true,
                ],
            ],
            [
                'cle'                         => 'magnat_mensuel',
                'label'                       => 'Magnat Mensuel',
                'duree_jours'                 => 31,
                'prix_xof'                    => 15000,
                'prix_mensuel_equivalent_xof' => 15000,
                'is_actif'                    => true,
                'ordre_affichage'             => 5,
                'description_courte'          => 'Pour les grands ateliers',
                'config' => [
                    'max_assistants'          => 2,
                    'max_membres'             => 5,
                    'max_clients_par_mois'    => 300,
                    'max_photos_vip_par_mois' => 15,
                    'max_factures_par_mois'   => 50,
                    'pts_par_client'          => 2,
                    'pts_par_commande'        => 2,
                    'pts_activation'          => 31,
                    'seuil_conversion_pts'    => 100000,
                    'photos_vip'             => true,
                    'facture_whatsapp'       => true,
                    'sauvegarde_auto'        => true,
                    'module_caisse'          => true,
                    'multi_ateliers'         => false,
                    'export_pdf'             => true,
                ],
            ],
            [
                'cle'                         => 'magnat_annuel',
                'label'                       => 'Magnat Annuel',
                'duree_jours'                 => 365,
                'prix_xof'                    => 150000,
                'prix_mensuel_equivalent_xof' => 12500,
                'is_actif'                    => true,
                'ordre_affichage'             => 6,
                'description_courte'          => 'Performance maximale',
                'config' => [
                    'max_assistants'          => 3,
                    'max_membres'             => 7,
                    'max_clients_par_mois'    => 500,
                    'max_photos_vip_par_mois' => 25,
                    'max_factures_par_mois'   => null,
                    'pts_par_client'          => 3,
                    'pts_par_commande'        => 3,
                    'pts_activation'          => 365,
                    'seuil_conversion_pts'    => 100000,
                    'photos_vip'             => true,
                    'facture_whatsapp'       => true,
                    'sauvegarde_auto'        => true,
                    'module_caisse'          => true,
                    'multi_ateliers'         => false,
                    'export_pdf'             => true,
                ],
            ],
        ];

        foreach ($plans as $plan) {
            NiveauConfig::updateOrCreate(['cle' => $plan['cle']], $plan);
        }

        $this->command->info('✅ NiveauxConfigSeeder : 6 plans insérés');
    }
}
