<?php

namespace Database\Seeders;

use App\Models\NiveauConfig;
use Illuminate\Database\Seeder;

class NiveauxConfigSeeder extends Seeder
{
    public function run(): void
    {
        // NOTE: ne pas utiliser json_encode() ici — le modèle a le cast 'array'
        // et encode lui-même. Passer des tableaux PHP bruts.
        $plans = [
            [
                'cle'                         => 'standard_mensuel',
                'label'                       => 'Standard Mensuel',
                'duree_jours'                 => 31,
                'prix_xof'                    => 3500,
                'prix_mensuel_equivalent_xof' => 3500,
                'is_actif'                    => false, // anciens plans — gardés mais masqués (refonte 2026)
                'ordre_affichage'             => 1,
                'description_courte'          => 'Idéal pour démarrer',
                'config' => [
                    'max_assistants'          => 0,
                    'max_membres'             => 0,
                    'max_clients_par_mois'    => 50,
                    'max_photos_vip_par_mois' => null,
                    'max_factures_par_mois'   => 0,
                    'pts_par_client'          => 1,
                    'pts_par_commande'        => 1,
                    'pts_activation'          => 31,
                    'seuil_conversion_pts'    => 10000,
                    'photos_vip'                 => false,
                    'facture_whatsapp'           => false,
                    'rappels_whatsapp_auto'      => true,
                    'sauvegarde_auto'            => false,
                    'module_caisse'              => false,
                    'multi_ateliers'             => false,
                    'max_sous_ateliers'          => 0,
                    'export_pdf'                 => true,
                    'facture_personnalisee'      => false,
                ],
            ],
            [
                'cle'                         => 'standard_annuel',
                'label'                       => 'Standard Annuel',
                'duree_jours'                 => 365,
                'prix_xof'                    => 35000,
                'prix_mensuel_equivalent_xof' => 2917,
                'is_actif'                    => false, // anciens plans — gardés mais masqués (refonte 2026)
                'ordre_affichage'             => 2,
                'description_courte'          => "Économisez avec l'annuel",
                'config' => [
                    'max_assistants'          => 1,
                    'max_membres'             => 1,
                    'max_clients_par_mois'    => 80,
                    'max_photos_vip_par_mois' => null,
                    'max_factures_par_mois'   => 0,
                    'pts_par_client'          => 1,
                    'pts_par_commande'        => 1,
                    'pts_activation'          => 365,
                    'seuil_conversion_pts'    => 10000,
                    'photos_vip'                 => false,
                    'facture_whatsapp'           => false,
                    'rappels_whatsapp_auto'      => true,
                    'sauvegarde_auto'            => false,
                    'module_caisse'              => false,
                    'multi_ateliers'             => true,
                    'max_sous_ateliers'          => 1,
                    'export_pdf'                 => true,
                    'facture_personnalisee'      => false,
                ],
            ],
            [
                'cle'                         => 'premium_mensuel',
                'label'                       => 'Premium Mensuel',
                'duree_jours'                 => 31,
                'prix_xof'                    => 7500,
                'prix_mensuel_equivalent_xof' => 7500,
                'is_actif'                    => false, // anciens plans — gardés mais masqués (refonte 2026)
                'ordre_affichage'             => 3,
                'description_courte'          => 'Le plus populaire',
                'config' => [
                    'max_assistants'          => 1,
                    'max_membres'             => 3,
                    'max_clients_par_mois'    => 100,
                    'max_photos_vip_par_mois' => 5,
                    'max_factures_par_mois'   => 25,
                    'pts_par_client'          => 1,
                    'pts_par_commande'        => 1,
                    'pts_activation'          => 31,
                    'seuil_conversion_pts'    => 45000,
                    'photos_vip'                => true,
                    'facture_whatsapp'          => true,
                    'rappels_whatsapp_auto'     => true,
                    'sauvegarde_auto'           => false,
                    'module_caisse'             => true,
                    'multi_ateliers'            => true,
                    'max_sous_ateliers'         => 1,
                    'export_pdf'                => true,
                    'facture_personnalisee'     => true,
                ],
            ],
            [
                'cle'                         => 'premium_annuel',
                'label'                       => 'Premium Annuel',
                'duree_jours'                 => 365,
                'prix_xof'                    => 75000,
                'prix_mensuel_equivalent_xof' => 6250,
                'is_actif'                    => false, // anciens plans — gardés mais masqués (refonte 2026)
                'ordre_affichage'             => 4,
                'description_courte'          => 'Premium avec sauvegarde auto',
                'config' => [
                    'max_assistants'          => 2,
                    'max_membres'             => 5,
                    'max_clients_par_mois'    => 150,
                    'max_photos_vip_par_mois' => 15,
                    'max_factures_par_mois'   => null,
                    'pts_par_client'          => 2,
                    'pts_par_commande'        => 2,
                    'pts_activation'          => 365,
                    'seuil_conversion_pts'    => 45000,
                    'photos_vip'                => true,
                    'facture_whatsapp'          => true,
                    'rappels_whatsapp_auto'     => true,
                    'sauvegarde_auto'           => true,
                    'module_caisse'             => true,
                    'multi_ateliers'            => true,
                    'max_sous_ateliers'         => 3,
                    'export_pdf'                => true,
                    'facture_personnalisee'     => true,
                ],
            ],
            [
                'cle'                         => 'magnat_mensuel',
                'label'                       => 'Magnat Mensuel',
                'duree_jours'                 => 31,
                'prix_xof'                    => 15000,
                'prix_mensuel_equivalent_xof' => 15000,
                'is_actif'                    => false, // anciens plans — gardés mais masqués (refonte 2026)
                'ordre_affichage'             => 5,
                'description_courte'          => 'Pour les grands ateliers',
                'config' => [
                    'max_assistants'          => 2,
                    'max_membres'             => 5,
                    'max_clients_par_mois'    => 300,
                    'max_photos_vip_par_mois' => 15,
                    'max_factures_par_mois'   => 50,
                    'pts_par_client'          => 2,
                    'pts_par_commande'        => 2,
                    'pts_activation'          => 31,
                    'seuil_conversion_pts'    => 100000,
                    'photos_vip'                => true,
                    'facture_whatsapp'          => true,
                    'rappels_whatsapp_auto'     => true,
                    'sauvegarde_auto'           => true,
                    'module_caisse'             => true,
                    'multi_ateliers'            => true,
                    'max_sous_ateliers'         => 3,
                    'export_pdf'                => true,
                    'facture_personnalisee'     => true,
                ],
            ],
            [
                'cle'                         => 'magnat_annuel',
                'label'                       => 'Magnat Annuel',
                'duree_jours'                 => 365,
                'prix_xof'                    => 150000,
                'prix_mensuel_equivalent_xof' => 12500,
                'is_actif'                    => false, // anciens plans — gardés mais masqués (refonte 2026)
                'ordre_affichage'             => 6,
                'description_courte'          => 'Performance maximale',
                'config' => [
                    'max_assistants'          => 3,
                    'max_membres'             => 7,
                    'max_clients_par_mois'    => 500,
                    'max_photos_vip_par_mois' => 25,
                    'max_factures_par_mois'   => null,
                    'pts_par_client'          => 3,
                    'pts_par_commande'        => 3,
                    'pts_activation'          => 365,
                    'seuil_conversion_pts'    => 100000,
                    'photos_vip'                => true,
                    'facture_whatsapp'          => true,
                    'rappels_whatsapp_auto'     => true,
                    'sauvegarde_auto'           => true,
                    'module_caisse'             => true,
                    'multi_ateliers'            => true,
                    'max_sous_ateliers'         => 7,
                    'export_pdf'                => true,
                    'facture_personnalisee'     => true,
                ],
            ],

            // ═══════════ NOUVEAUX PLANS — grille 2026 (prix provisoires) ═══════════
            // Limites galerie : max_creations_vitrine (photos publiables) + visible_galerie.
            [
                'cle'                         => 'free',
                'label'                       => 'Free',
                'duree_jours'                 => 32000,
                'prix_xof'                    => 0,
                'prix_mensuel_equivalent_xof' => 0,
                'is_actif'                    => true,
                'ordre_affichage'             => 10,
                'description_courte'          => 'Découverte — sans engagement',
                'config' => [
                    'max_assistants'          => 0,
                    'max_membres'             => 0,
                    'max_clients_par_mois'    => 10,
                    'max_commandes_par_mois'  => 10,
                    'max_photos_vip_par_mois' => 0,
                    'max_factures_par_mois'   => 5,
                    'pts_par_client'          => 1,
                    'pts_par_commande'        => 1,
                    'pts_activation'          => 31,
                    'seuil_conversion_pts'    => 10000,
                    'photos_vip'              => false,
                    'facture_whatsapp'        => false,
                    'rappels_whatsapp_auto'   => true,
                    'sauvegarde_auto'         => false,
                    'module_caisse'           => false,
                    'multi_ateliers'          => false,
                    'max_sous_ateliers'       => 0,
                    'export_pdf'              => false,
                    'facture_personnalisee'   => true,
                    'max_creations_vitrine'   => 5,
                    'visible_galerie'         => false,
                ],
            ],
            [
                'cle'                         => 'atelier_mensuel',
                'label'                       => 'Atelier Mensuel',
                'duree_jours'                 => 31,
                'prix_xof'                    => 1200,
                'prix_mensuel_equivalent_xof' => 1200,
                'is_actif'                    => true,
                'ordre_affichage'             => 11,
                'description_courte'          => 'Recommandé',
                'config' => [
                    'max_assistants'          => 1,
                    'max_membres'             => 0,
                    'max_clients_par_mois'    => 50,
                    'max_commandes_par_mois'  => 50,
                    'max_photos_vip_par_mois' => null,
                    'max_factures_par_mois'   => null,
                    'pts_par_client'          => 1,
                    'pts_par_commande'        => 1,
                    'pts_activation'          => 31,
                    'seuil_conversion_pts'    => 45000,
                    'photos_vip'              => true,
                    'facture_whatsapp'        => true,
                    'rappels_whatsapp_auto'   => true,
                    'sauvegarde_auto'         => true,
                    'module_caisse'           => true,
                    'multi_ateliers'          => false,
                    'max_sous_ateliers'       => 0,
                    'export_pdf'              => false,
                    'facture_personnalisee'   => true,
                    'max_creations_vitrine'   => 15,
                    'visible_galerie'         => true,
                ],
            ],
            [
                'cle'                         => 'atelier_annuel',
                'label'                       => 'Atelier Annuel',
                'duree_jours'                 => 365,
                'prix_xof'                    => 12000,
                'prix_mensuel_equivalent_xof' => 1000,
                'is_actif'                    => true,
                'ordre_affichage'             => 12,
                'description_courte'          => 'Recommandé — 2 mois offerts',
                'config' => [
                    'max_assistants'          => 1,
                    'max_membres'             => 0,
                    'max_clients_par_mois'    => 50,
                    'max_commandes_par_mois'  => 50,
                    'max_photos_vip_par_mois' => null,
                    'max_factures_par_mois'   => null,
                    'pts_par_client'          => 1,
                    'pts_par_commande'        => 1,
                    'pts_activation'          => 365,
                    'seuil_conversion_pts'    => 45000,
                    'photos_vip'              => true,
                    'facture_whatsapp'        => true,
                    'rappels_whatsapp_auto'   => true,
                    'sauvegarde_auto'         => true,
                    'module_caisse'           => true,
                    'multi_ateliers'          => false,
                    'max_sous_ateliers'       => 0,
                    'export_pdf'              => false,
                    'facture_personnalisee'   => true,
                    'max_creations_vitrine'   => 15,
                    'visible_galerie'         => true,
                ],
            ],
            [
                'cle'                         => 'master_mensuel',
                'label'                       => 'Master Mensuel',
                'duree_jours'                 => 31,
                'prix_xof'                    => 2500,
                'prix_mensuel_equivalent_xof' => 2500,
                'is_actif'                    => true,
                'ordre_affichage'             => 13,
                'description_courte'          => 'Premium',
                'config' => [
                    'max_assistants'          => 2,
                    'max_membres'             => 1,
                    'max_clients_par_mois'    => 150,
                    'max_commandes_par_mois'  => 150,
                    'max_photos_vip_par_mois' => 15,
                    'max_factures_par_mois'   => null,
                    'pts_par_client'          => 2,
                    'pts_par_commande'        => 2,
                    'pts_activation'          => 31,
                    'seuil_conversion_pts'    => 100000,
                    'photos_vip'              => true,
                    'facture_whatsapp'        => true,
                    'rappels_whatsapp_auto'   => true,
                    'sauvegarde_auto'         => true,
                    'module_caisse'           => true,
                    'multi_ateliers'          => true,
                    'max_sous_ateliers'       => 1,
                    'export_pdf'              => true,
                    'facture_personnalisee'   => true,
                    'max_creations_vitrine'   => 30,
                    'visible_galerie'         => true,
                ],
            ],
            [
                'cle'                         => 'master_annuel',
                'label'                       => 'Master Annuel',
                'duree_jours'                 => 365,
                'prix_xof'                    => 25000,
                'prix_mensuel_equivalent_xof' => 2083,
                'is_actif'                    => true,
                'ordre_affichage'             => 14,
                'description_courte'          => 'Premium — 2 mois offerts',
                'config' => [
                    'max_assistants'          => 2,
                    'max_membres'             => 1,
                    'max_clients_par_mois'    => 150,
                    'max_commandes_par_mois'  => 150,
                    'max_photos_vip_par_mois' => 15,
                    'max_factures_par_mois'   => null,
                    'pts_par_client'          => 2,
                    'pts_par_commande'        => 2,
                    'pts_activation'          => 365,
                    'seuil_conversion_pts'    => 100000,
                    'photos_vip'              => true,
                    'facture_whatsapp'        => true,
                    'rappels_whatsapp_auto'   => true,
                    'sauvegarde_auto'         => true,
                    'module_caisse'           => true,
                    'multi_ateliers'          => true,
                    'max_sous_ateliers'       => 1,
                    'export_pdf'              => true,
                    'facture_personnalisee'   => true,
                    'max_creations_vitrine'   => 30,
                    'visible_galerie'         => true,
                ],
            ],
        ];

        foreach ($plans as $plan) {
            NiveauConfig::updateOrCreate(['cle' => $plan['cle']], $plan);
        }

        $this->command->info('✅ NiveauxConfigSeeder : 6 plans insérés');
    }
}
